name: Publish Documentation
on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Install DocFX
        run: dotnet tool install -g docfx

      - name: Build Documentation (init, metadata, build)
        run: |
          docfx init -y
          docfx metadata docfx.json
          docfx build

      - name: Upload generated site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-site
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true
